# the name of your track or event
name = "Gaming, Metaverse, and Video"

# the name of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "Jonathan Victor, Anshuman Prasad"

# the start date of the event
date = "2022-10-30"

# how many days the event lasts (1 - N)
days = 1

venueName = "Arion"

# the event times (shows up in the event card)
times = "10:00 - 16:00"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """
  Demos of how IPFS can save bandwidth and increase flexibility. Talks about directions for the future.
"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 10:00
# - recommended lunch: 13:00
# - recommended end:   16:00 (On 30 Oct, 1h Camp wrapup begins at 16:00)
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon

[[timeslots]]
startTime="10:00"
speakers=["Jonathan Victor"]
title="Track Intro"
description="Opening talk to introduce the track and ideas."

[[timeslots]]
startTime="10:15"
speakers=["Adam Grodzki"]
title="Bringing web3 primitives to Unreal Engine"
description="Studio 3S will share their insights around how they're supercharging Unreal Engine with web3 primitives."

[[timeslots]]
startTime="10:45"
speakers=["Taivo Pungas"]
title="Hands-on: Integrating web3 with Unity"
description="The NFTPort team will give a hands on workshop demoing how you can use web3 tech natively with Unity."

[[timeslots]]
startTime="11:30"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="11:45"
speakers=["Crystal Mills", "Matt Wisniewski", "Pasquale Sorrentino", "Shannon Wells"]
title="Live streaming infra - video and real time challenges in web3"
description="Crystal Mills will moderate a discussion across teams building on streaming technology in web3."

[[timeslots]]
startTime="12:30"
speakers=["J Chris Anderson", "David Choi", "Changwé Mutakasha"]
title="Onboarding dapps and game storage to web3"
description="An open discussion with the leads of web3.storage on the challenges and opportunities they've observed building scalable infrastructure for web3."

[[timeslots]]
startTime="13:00"
speakers=[]
title="Lunch"
description=""

[[timeslots]]
startTime="14:00"
speakers=["Tobias Petrasch"]
title="Hammerspace: The Metaverse backpack"
description="Tobias will give an overview of Hammerspace- along with the motivations, challenges, and solutions they've encountered building tools to enable cross platform assets."

[[timeslots]]
startTime="14:15"
speakers=["E. Désiré Nzengou"]
title="Bringing Space Data to the Metaverse"
description="Participate to this session to find out where Space meets the Metaverse, and get a sneak peek into the sea of opportunities for startups bridging space technologies and space data, web3, and deep tech with this speaker from the European Union Agency for the Space Programme (EUSPA)."


[[timeslots]]
startTime="14:30"
speakers=["Yondon Fu"]
title="Video and Metadata Standards with Livepeer"
description="Shannon will share the learnings and observations from Livepeer, as they work across ecosystems to help steward shared open standards."

[[timeslots]]
startTime="15:00"
speakers=["Daryl Lim"]
title="Metapals: Importance of usability in Web3"
description="Metapals COO Daryl Lim will share useful insights the team gathered since embarking on their journey early this year, especially on converting and helping non-crypto users transition into the web3."

[[timeslots]]
startTime="15:30"
speakers=["Justin Melillo", "Nathalie Nunez", "Matthew Bradley", "Metageist", "Matt Marshall"]
title="World Builders"
description="A roundtable discussion with creators building ownable metaverses"
